### ISSUE TITLE
User logging out is not prompted at the other end

### ISSUE THREAD

**Issue by shivam-tripathi** [kt1996/ChatApplication#1]
Last time when I used this app (I rarely use Windows), I found that when an user logs out, the other user(s) in the chat are not prompted, even though the session of the logging out user is ended. I feel it would be better if others come to know that there is no one out there now.

**Comment by kt1996** [comment]
Hey Shivam,
          Thanks for the feedback, due to a inconsistency in code, the users weren't being notified. It has been resolved in the latest commit. Thanks :)

**Comment by shivam-tripathi** [comment]
Ok. Good job :+1:
